import { BASE_URL, AUTH_SIGNUP, AUTH_LOGIN, AUTH_LOGOUT, AUTH_FORGOT, AUTH_RESET, ADMISSIONS_SUBMIT, ADMISSIONS_STATUS, NOTIFICATIONS_SAVE_PUSH_TOKEN,NOTIFICATIONS_SAVE, NOTIFICATIONS_GET_ALL, NOTIFICATIONS_DELETE, NOTIFICATIONS_MARK_AS_READ,STUDENT_PROFILE, STUDENT_INFO_HOME, STUDENT_INFO_FEES, STUDENT_INFO_ATTENDANCE, STUDENT_INFO_GRADE, STUDENT_INFO_REPORT, EVENTS_UPCOMING, FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID,  FIREBASE_STORAGE_BUCKET, FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID, FIREBASE_MEASUREMENT_ID, MOMO_API_URL, MOMO_API_KEY, MOMO_API_SECRET_KEY, MOMO_PHONE_NUMBER, MOMO_ACCOUNT_NAME, BANK_API_URL, BANK_API_KEY, BANK_API_SECRET_KEY, BANK_ACCOUNT_NAME, BANK_ACCOUNT_NUMBER, BANK_NAME, BANK_BRANCH_NAME, GOOGLE_MAPS_API_KEY } from '@env';


export const appConfig = {
    APP_VERSION: '1.0.0',
};

export const schoolInfo = {
  SCHOOL_NAME: 'OFORI-ATTA INTERNATIONAL SCHOOL',
  SCHOOL_SHORT_NAME: 'OAIS',
  WATERMARK: 'QUINTESSENCE',
  MISSION_STATEMENT: 'Ofori Atta International School is a Christian based Educational Center which seeks to pass on Spiritual and Academic Excellence to its pupils.',
  VISION: 'To be a Standard in the delivery of Wholesome Education.',
  SCHOOL_MOTTO: 'QUINTESSENCE',
  SCHOOL_PHONE: '+233 553 558 274 / +233 249 739 773',
  SCHOOL_LOGO: './assets/icons/OAIS-logo.png',
  SCHOOL_ADDRESS: 'P.O. Box 123, Apowa, Takoradi, Ghana',
  SCHOOL_EMAIL: 'oforiattainternationalschool@gmail.edu',
  SCHOOL_WEBSITE: 'www.oais.edu.gh'
};

export const APIConfig = {
  BASE_URL: BASE_URL,
  AUTH: {
    SIGNUP: AUTH_SIGNUP,
    LOGIN: AUTH_LOGIN,
    LOGOUT: AUTH_LOGOUT,
    FORGOT_PASSWORD: AUTH_FORGOT,
    RESET_PASSWORD: AUTH_RESET,
  },
  ADMISSIONS: {
    SUBMIT: ADMISSIONS_SUBMIT,
    STATUS: ADMISSIONS_STATUS,
  },
  NOTIFICATIONS: {
    SAVE_PUSH_TOKEN: NOTIFICATIONS_SAVE_PUSH_TOKEN,
    SAVE_ALL: NOTIFICATIONS_SAVE,
    GET_ALL: NOTIFICATIONS_GET_ALL,
    DELETE: NOTIFICATIONS_DELETE,
    MARK_AS_READ: NOTIFICATIONS_MARK_AS_READ,
  },
  STUDENT_INFO: {
    PROFILE: STUDENT_PROFILE,
    HOME: STUDENT_INFO_HOME,
    FEES: STUDENT_INFO_FEES,
    ATTENDANCE: STUDENT_INFO_ATTENDANCE,
    GRADE: STUDENT_INFO_GRADE,
    REPORT: STUDENT_INFO_REPORT,
  },
  EVENTS: {
    UPCOMING: EVENTS_UPCOMING,
  },
};

export const googleMapsConfig = {
  API_KEY: GOOGLE_MAPS_API_KEY,
  URL: `https://maps.googleapis.com/maps/api/js?key=${GOOGLE_MAPS_API_KEY}&libraries=places`,
};

export const firebaseConfig = {
  API_KEY: FIREBASE_API_KEY,
  AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  PROJECT_ID: FIREBASE_PROJECT_ID,
  STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: FIREBASE_MESSAGING_SENDER_ID,
  APP_ID: FIREBASE_APP_ID,
  MEASUREMENT_ID: FIREBASE_MEASUREMENT_ID,
};

export const paymentConfig = {
  MOMO_PAYMENT: {
    BASE_URL: MOMO_API_URL,
    APP_ID: MOMO_API_KEY,
    SECRET_KEY: MOMO_API_SECRET_KEY,
    PHONE_NUMBER: MOMO_PHONE_NUMBER,
    ACCOUNT_NAME: MOMO_ACCOUNT_NAME,
  },
  BANK_PAYMENT: {
    BASE_URL: BANK_API_URL,
    API_KEY: BANK_API_KEY,
    SECRET_KEY: BANK_API_SECRET_KEY,
    BANK_NAME: BANK_NAME,
    ACCOUNT_NUMBER: BANK_ACCOUNT_NUMBER,
    ACCOUNT_NAME: BANK_ACCOUNT_NAME,
    BRANCH: BANK_BRANCH_NAME,
  }
};